### PR TITLE
proposer: fix revert

### LINKED ISSUE #21: no blocks finalized after 21000 blocks
when i query `cast block finalized --rpc-url http://localhost:9545/` i still get 0 blocks finalized, meaning no txs are finalized. according to the [OP docs: “If the transaction isn’t finalized or safe, it’s unsafe.”
](https://community.optimism.io/docs/protocol/txn-flow/#posting-to-l1)

[Here is a gist with relevant logs](https://gist.github.com/jcstein/8b394ab7d52b2185711a323ff6d633da). This can be reproduced on #20

### LINKED ISSUE #23: `proposer tx successfully published but reverted`
image

The message "`proposer tx successfully published but reverted`" shows every time the proposer submits a transaction. [Here are the logs](https://gist.github.com/jcstein/1eec19ea37dd69c03cf92b39402ca525) (occurs 2641 times) running on #20 at the height 26908 on the L2, with the DA height at 5325

### PR DESCRIPTION
**Pull request by tuxcanfly**
This PR fixes #23 which was happening because the proposer transaction was failing with:

`proposer tx successfully published but reverted`

There were two issues here:

* Proposer transaction read from celestia is not supported, because unlike batcher transaction, the data is posted to the smart contract rather than to calldata directly, so we cannot read proposer data without reading the smart contract. To fix this, we are going to restore posting the data to ethereum instead of celestia. This should be tracked in #27
* Proposer transaction was reverting because of insufficient gas limit. The limit has been bumped.

There is some hacky code here because both batcher and proposer reuse the same code for sending out the transaction, so we need to have a ugly if around the celestia transaction. Will be thinking through improvements to this.

### CODE REVIEW

**Comment by jcstein** [comment]
nice! this is working as expected for me

scrot 2023-05-01 at 11 04 22 PM

**Review by jcstein — APPROVED** [review]

File: op-proposer/proposer/l2_output_submitter.go [hunk 1]
```diff
@@ -332,7 +332,7 @@ func (l *L2OutputSubmitter) sendTransaction(ctx context.Context, output *eth.Out
 		To:     &l.l2ooContractAddr,
 		// Use manual limit as proposer tx data may be to small
 		// t=2023-04-28T00:59:37+0000 lvl=warn msg="estimating gas"                     service=proposer gas=87698
-		GasLimit: 100000,
```
Comment (Ferret-san) [inline op-proposer/proposer/l2_output_submitter.go:335]: I think we can make the `GasLimit` 0 now that it works, so that transaction manager can estimate the gas limit

**Review by jcstein — APPROVED** [review]
whoops

File: op-service/txmgr/txmgr.go [hunk 2]
```diff
@@ -213,38 +213,41 @@ func (m *SimpleTxManager) send(ctx context.Context, candidate TxCandidate) (*typ
 		ctx, cancel = context.WithTimeout(ctx, m.cfg.TxSendTimeout)
 		defer cancel()
 	}
-	res, err := m.daClient.SubmitPFB(ctx, m.namespaceId, candidate.TxData, 20000, 700000)
-	if err != nil {
-		m.l.Warn("unable to publish tx to celestia", "err", err)
-		return nil, err
-	}
-	fmt.Printf("res: %v\n", res)
+	if candidate.To.Hex() == "0xfF00000000000000000000000000000000000000" {
```
Comment (Ferret-san) [inline op-service/txmgr/txmgr.go:221]: Add a comment to clarify why we check for this address

**Review by Ferret-san — APPROVED** [review]

File: op-proposer/proposer/l2_output_submitter.go (hunk 1 above)
Comment (tuxcanfly) [reply op-proposer/proposer/l2_output_submitter.go:335]: Thanks, done

File: op-service/txmgr/txmgr.go (hunk 2 above)
Comment (tuxcanfly) [reply op-service/txmgr/txmgr.go:221]: Added explanation as a TODO note.
